name: Keep API Warm

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  keep-warm:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP request to keep API warm
        run: |
          curl -s --verbose https://shopping-website-12o1.onrender.com/new_arrivals